# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Test "glimpse-video-control" Docker image

on:
  push:
    branches: [release, dev]
  pull_request:
    branches: [release, dev]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rpitv/glimpse-video-control

jobs:
  build-and-test-image:
    name: Build and Test Image
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies locally
        run: |
          cd control
          npm ci

      - name: Lint
        run: |
          cd control
          npm run lint

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./control
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/rpitv/glimpse-video-control:${{ github.run_id }}
